defaults:
  - sft.yaml

policy:
  model_name: "Qwen/Qwen2.5-VL-7B-Instruct"
  tokenizer:
    name: ${policy.model_name} ## specify if you'd like to use a tokenizer different from the model's default
    is_tokenizer_processor: true
  train_global_batch_size: 16
  train_micro_batch_size: 1
  max_total_sequence_length: 1024
  precision: "bfloat16"
  fsdp_offload_enabled: false
  activation_checkpointing_enabled: false

data:
  max_input_seq_length: ${policy.max_total_sequence_length}
  dataset_name: "clevr_cogent"
  add_bos: true
  add_eos: true
  add_generation_prompt: false
  split: trainA
  seed: 42
  task_name: "clevr-cogent"
  prompt_file: null

logger:
  log_dir: "logs"  # Base directory for all logs
  wandb_enabled: false # Make sure you do a ``wandb login [Your API key]'' before running
  tensorboard_enabled: true
  monitor_gpus: true  # If true, will monitor GPU usage and log to wandb and/or tensorboard
  wandb:
    project: "sft-dev"
    name: "sft-dev-${data.dataset_name}"
  tensorboard:
    log_dir: "tb_logs-sft-dev-${data.dataset_name}"
  gpu_monitoring:
    collection_interval: 10  # How often to collect GPU usage metrics (in seconds)
    flush_interval: 10  # How often to flush GPU usage metrics to the loggers (in seconds)

cluster:
  gpus_per_node: 1
  num_nodes: 1
